name: flutter_autoupdate
description: Easily add auto update functionality to your Flutter application
version: 1.0.0
author: Victor See<hello@imvictor.me>
homepage: https://github.com/feedmepos/flutter_autoupdate

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  app_installer: ^1.1.0
  crypto: ^3.0.3
  dio: ^5.4.3
  flutter:
    sdk: flutter
  flutter_app_installer: ^1.0.0
  path_provider: ^2.1.3
  url_launcher: ^6.3.0
  version: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
